[package]
name = "eclipse-syscall"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "eclipse_syscall"
path = "src/lib.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
