[package]
name = "populate-eclipsefs"
version = "1.0.0"
edition = "2021"

[dependencies]
eclipsefs-lib = { path = "../eclipsefs-lib" }
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.4"
