[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = "qemu-system-x86_64"
rustflags = ["-C", "code-model=large", "-C", "relocation-model=static"]
