[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=--entry=_start",
  "-C", "link-arg=-static",
  "-C", "relocation-model=static",
  "-C", "code-model=kernel",
  "-C", "link-arg=--no-pie",
  "-C", "link-arg=--no-dynamic-linker",
]

[build]
target = "x86_64-unknown-none"