[package]
name = "eclipse-libc-internal"
version = "0.1.0"
edition = "2021"

[lib]
name = "eclipse_libc_internal"
crate-type = ["staticlib", "rlib"]

[dependencies]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
