[package]
name = "smithay_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse-libc = { package = "eclipse-libc-internal", path = "../../eclipse_kernel/userspace/libc" }
embedded-graphics = "0.8.1"

[[bin]]
name = "smithay_app"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
