[package]
name = "filesystem_service"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse-libc = { path = "../libc" }

[[bin]]
name = "filesystem_service"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
