[package]
name = "filesystem_service"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse-libc = { path = "../libc" }
eclipsefs-lib = { path = "../../../eclipsefs-lib", default-features = false }
linked_list_allocator = { version = "0.10.5", default-features = false, features = ["use_spin"] }

[[bin]]
name = "filesystem_service"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
