[package]
name = "std_test"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse_std = { path = "../eclipse_std" }
eclipse-syscall = { path = "../../eclipse-syscall" }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
