[package]
name = "eclipse_std"
version = "0.2.0"
edition = "2021"

[dependencies]
eclipse-syscall = { path = "../../eclipse-syscall" }
libc = { package = "eclipse-libc-posix", path = "../../eclipse-libc" }

[features]
panic-handler = []
alloc-error-handler = []
[lib]
name = "eclipse_std"
path = "src/lib.rs"

