[package]
name = "eclipse_std"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse-libc = { path = "../../eclipse_kernel/userspace/libc" }

[lib]
name = "eclipse_std"
path = "src/lib.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
