[package]
name = "eclipse-libc"
version = "0.1.0"
edition = "2021"

[dependencies]
eclipse-syscall = { path = "../eclipse-syscall" }

[features]
default = ["allocator"]
allocator = []
panic_handler = []

[lib]
name = "eclipse_libc"
path = "src/lib.rs"
crate-type = ["rlib"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
